# Generated by Django 4.1.1 on 2022-11-15 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7)),
                ('accept_status', models.CharField(choices=[('draft', 'draft'), ('decline', 'decline'), ('accept', 'accept'), ('pending', 'pending')], default=('draft', 'draft'), max_length=15)),
                ('work_start_date', models.DateField()),
                ('work_end_date', models.DateField()),
                ('deadline', models.DateField()),
                ('project_client_budget', models.IntegerField(default=0)),
                ('project_eastemate_cost', models.IntegerField(default=0)),
                ('sort_description', models.CharField(max_length=300)),
                ('description', django_quill.fields.QuillField()),
                ('complete_per', models.FloatField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='project_file')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('upd_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.categories')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7)),
                ('due', models.CharField(choices=[('on due', 'On Due'), ('overdue', 'Overdue'), ('done', 'Done')], default=1, max_length=7)),
                ('description', django_quill.fields.QuillField()),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('complete_per', models.FloatField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('file', models.FileField(upload_to='project_task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('worker', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7)),
                ('description', django_quill.fields.QuillField()),
                ('file', models.FileField(max_length=254, upload_to='project_submission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('stuck', 'Stuck'), ('working', 'Working'), ('done', 'Done')], default=1, max_length=7)),
                ('due', models.CharField(choices=[('on due', 'On Due'), ('overdue', 'Overdue'), ('done', 'Done')], default=1, max_length=7)),
                ('today_start_work', models.TimeField()),
                ('today_end_work', models.TimeField()),
                ('total_data_entry_today', models.CharField(blank=True, default=0, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('complete_per', models.FloatField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('file', models.FileField(upload_to='task_issues')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
